"""Build swipe_ledger.csv from raw/_ledger_selection.jsonl with concept-level analyst annotations.
Copy fields (hook/headline/body_excerpt) are verbatim from the Meta Ad Library JSON; analysis fields are analyst coding."""
import json, csv, os, re
D = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
VIEWED = set(f[:-4] for f in os.listdir(D + "/thumbs") if f.endswith(".jpg") and not f.startswith(("s_", "sheet")))
# ---------- landing page patterns (from raw/landing/*.txt renders, 2026-10-03) ----------
LP = [
 ("skinglowmagazine.com/top5-body-oil", "Fake-editorial comparison listicle (labelled 'Advertorial'): 'Top 5 Body Oils for Crepey, Dry & Dimpled Skin of 2026 — Tested & Reviewed by a Dermatologist', byline 'Dr. Sarah Mitchell, Board-certified Dermatologist'; ranks Evora #1 (A+) over Eraé, Besque (D+), Goda (C), Cavo (D); hormone/structural-cause education; all CTAs 'CHECK AVAILABILITY ➜' to evorabody PDP (raw/landing/skinglow_top5.txt)"),
 ("evorabody.com/pages/listicle8", "7-reasons listicle: 'Dermatologists Shocked: This Cold-Pressed Body Oil Can Soften Years of Crepey Skin. Here's 7 Reasons Why.'; estrogen/collagen + oil-matches-barrier mechanism; '50% OFF + FREE SHIPPING' warehouse clearance; 4.8/5 (1,113 reviews), Trustpilot badge; 'Sell-out Risk: Very High'; CTA 'CHECK AVAILABILITY' (WebFetch + raw/landing/evora_listicle8.txt)"),
 ("quiz.evorabody.com", "Quiz funnel: 'Take This 1-Minute Quiz To Claim Your $105 Discount!'; 'Most users see first visibly results in just 3-4 weeks'; Q1 age bracket (Under 40 / 40-49 / 50-59 / 60-69 / Over 70) (raw/landing/evora_quiz.txt)"),
 ("es.evorabody.com", "Spanish-language PDP variant (not rendered)"),
 ("evorabody.com/es/", "Spanish-language PDP variant (not rendered)"),
 ("evorabody.com/products/botanical-body-oil-cc", "PDP variant URL (-cc) (not rendered)"),
 ("evorabody.com/products/botanical-body-oil", "Shopify PDP: 'Botanical Body Oil™' $49.00 (compare $69.00); 'WAREHOUSE CLEARANCE: UP TO 50% OFF'; 1/2/3-bottle tiers $49 / $39 / $34 per bottle; subscription pre-selected ('Refill Ships in 30 Days') with 'BUY ONCE - NO SAVINGS →' link; '89% sold' scarcity bar; 90-Day Money-Back Guarantee; (1,560) reviews, 'Isabelle and 50.000+ others purchased'; mechanism block (oil 'melts directly through the skin's lipid barrier'); 6 hero ingredients + full INCI; Day 1 → Week 8-12 results timeline; 'Why Evora? vs Others' table; FAQ (raw/landing/evora_pdp.txt)"),
 ("goda.co/products/silk-body-oil", "Shopify PDP: 'Goda® Silk Body Oil' $59 (compare $98); Buy 1 $37 / Buy 2 Get 1 FREE $59 / Buy 3 Get 2 FREE $88 + free gifts; countdown timer; 'ONLY 12 LEFT', '14 customers are viewing'; 30-Day MBG; subscription default + 'BUY ONCE - NO SAVINGS'; 4.8/5 (5,460 reviews), 'Trusted by 95,000+'; stat-claims ('89% Reduction on sagging skin and thigh'); 'Esthetician Approved' (raw/landing/goda_silk_body_oil.txt)"),
 ("godaperfume.com", "Goda PDP via godaperfume.com domain (redirect; not separately rendered — see goda.co PDP)"),
 ("goda.co/pages/crepey", "Goda crepey-skin education page (not rendered)"),
 ("nordbody.com/pages/7-reasons", "Listicle advertorial '7 Reasons Women Are Switching to Peptides to Firm Crepey Skin in 2026', byline 'Olivia Thompson'; 'crepey skin is a structure problem' + 'creams ~80% water, oil penetrates' mechanism; triple-peptide body oil; '91% said...' 8-week consumer panel (raw/landing/nord_7reasons.txt)"),
 ("nordbody.com/pages/down-in-weight", "First-person GLP-1 advertorial 'Down 38 Pounds — and I Still Couldn't Wear the Bikini...' by 'Jenna R. · 52'; Week 0 / Week 6 arm photos; '$100 firming creams: up to 80% water' comparison table (raw/landing/nord_down_in_weight.txt)"),
 ("nordbody.com/pages/quiz", "Quiz funnel (not rendered)"),
 ("nordbody.com", "NØRD BODY advertorial/listicle variant (not rendered; see 7-reasons page)"),
 ("vitaecharm.com", "VitaeCharm PDP/advertorial: 'Body oil formulated for crepey skin... 90 days or full refund'; Buy 1 $32 / Buy 2 Get 1 $19 ea / Buy 3 Get 2 $15 ea + up to 4 free gifts; subscription default; 'basal cell layer', 'penetrates 5 layers', '100% pure oil (not water that evaporates)' (raw/landing/vitaecharm_10reasons.txt — advertorial URL redirected to homepage on render)"),
 ("besque.co", "Besque PDP: 'Besque® Magic Body Oil XL - 200ml' $120 (subscription $78 = 35% off per ads); 7 cold-pressed oils listed; '500,000+ Happy Customers'; Trustpilot (raw/landing/besque_magic_body_oil.txt)"),
 ("drmtlgy.com/products/retinol-body-lotion", "DRMTLGY PDP: Retinol Body Lotion 6 oz $36 (auto-ship $27, 25% off); 'Firms + Enhances Elasticity'; '...improve the look of crepey skin'; 513 reviews; free mask on $75+; '151 people have this in their cart' (raw/landing/drmtlgy_retinol_body.txt)"),
 ("drmtlgy.com", "DRMTLGY collection/advertorial page (not rendered)"),
 ("oseamalibu.com", "OSEA PDP: Undaria Algae™ Body Oil $100 → $84 (subscribe $75.60); 4.7/5 (3,773 reviews); 'Clean Meets Clinical®'; 'clinically shown to visibly improve elasticity'; 30-Day MBG (raw/landing/osea_undaria.txt)"),
 ("saeskyn.com", "Saeskyn PDP: Korean Wrinkle Bounce Multi Balm Stick $29.95 (reg $59.90), 'LABOR DAY SALE ENDS IN' countdown, BOGO tiers, 60-Day Guarantee, 'Trusted By 50,000+', Salmon DNA/Jeju claims (raw/landing/saeskyn_balm.txt)"),
 ("try-turmskin.com/pages/7reasons", "Listicle '7 Reasons Why Women Over 30 Use This Hyaluronic Acid Serum...' by 'Maria Thompson'; up to 60% off Fall Sale, 30-day MBG (WebFetch)"),
 ("felineskinscience.com", "Feline Skinscience PDP (404 at render time; site banner 'BUY 1, GET 1 FREE', '60 DAYS MONEY BACK GUARANTEE', 'TRUSTED BY 100,000+ WOMEN')"),
 ("trymiamimd.com", "Miami MD affiliate prelander/VSL/quiz (affId params); not rendered (proxy refused plain-HTTP URL)"),
 ("froyaorganics.com", "Frøya Organics long-form page: '854,850+ WOMEN SAID GOODBYE TO WRINKLES (4.9/5)', 'Visibly Glowing Skin in as Little as 48 Hours', 'TRY IT RISK-FREE - SAVE 40%', code FALLSALE (raw/landing/froya_balms.txt)"),
 ("emilycarterblog.com", "Fake-editorial comparison 'I Tried 5 Different ‘Firming’ Creams. Only One Actually Worked.' by 'Emily Carter'; names Gold Bond, Crépe Erase, StriVectin, Miami MD as losers; winner 'Cellu Deep Firming Body Cream' 9.6/10; 60-day MBG (raw/landing/emilycarter_comparison.txt)"),
 ("theskinmag.com", "Fake-news advertorial 'THE SKINCARE MAGAZINE' — 'If Your Arms, Neck, Or Hands Look Crepey This 1973 Nobel Prize Discovery Explains Why...' by 'Laura Benton'; product revealed as Noor's Copper Peptide Body Repair Cream; '2-minute' ritual (raw/landing/theskinmag_cpbc.txt)"),
 ("beekman1802.com", "Beekman 1802 PDP: Milk RX Body Crepe Smoothing Cream 6 fl oz $55 (S&S $46.75); 'goat milk exosomes, COLLAGEN++'; 140 reviews (raw/landing/beekman_crepe.txt)"),
 ("tryorgatics.com", "Orgatics advertorial for 'Ceylon-Style Inside-Out Skin Support Softgels' (not rendered)"),
 ("beautyfrombees.ca", "Beauty From Bees (Canada) body-serum PDP (not rendered)"),
 ("remedyskin.com", "Remedy Skin PDP (not rendered)"),
]
def lp(u):
    for k, v in LP:
        if k in (u or ""): return v
    return "no landing URL in library record" if not u else "not rendered"
# ---------- concept annotations: (match regex on normalized title/body, dict) ----------
def A(angle, desire, problem, mech, promise, aware, big, story, visual=""):
    return dict(angle=angle, desire=desire, problem_framing=problem, mechanism=mech, promise_claim=promise,
                awareness_level=aware, big_idea=big, story_structure=story, visual_default=visual)
WAT = "Water-based creams/lotions evaporate & sit on surface; oil melts through the lipid barrier to 'the layer where crepey skin starts'; six cold-pressed oils replace lipids skin 'stopped making' after 50/menopause"
EVORA = [
 (r"437 orders|orders in last hour", A("Scarcity / viral-demand 'live update'", "Not miss out on the product other women are rushing to buy", "Implicit: 'reaching where lotions never could' (lotions fail)", "Only implied ('actually reaching where lotions never could')", "None explicit beyond virality; guarantee in link description", "Product-aware / most-aware (assumes prior 'watching or researching')", "Live stock-drop bulletin: the viral body oil is selling out right now", "No story — breaking-news/'LIVE UPDATE' format with fabricated-looking urgency stats ('83% of this batch sold in the last 90 minutes')", "Image viewed for 4075847312708860: product line-up + headline 'EVORA SENIOR SALE – ENDS MIDNIGHT' and '50% OFF SITEWIDE + EXTRA 12% WITH CODE SENIOR62' (creative content differs from copy); other variants not viewed")),
 (r"heres what actually works|lo que s.? ?funciona", A("Story-video shell (one caption, many different videos)", "Varies by video: insider luxury secret, life-event transformation", "In video (not in text)", "In video (not in text)", "Body text only: 'THIS is what Oil does for your skin…'", "Unaware → problem-aware (story-first, product late)", "Short-form story reels with the oil as the twist; same headline/caption used as a testing wrapper for many videos", "Video story; text is a 7-word curiosity caption", "9:16 video. Thumbnails viewed for 12 IDs: (a) AI-generated cinematic story scenes with burned-in captions ('Three years inside', 'My son got married in June,', 'My ex-husband', 'Every August for nineteen years,', a stylised blue-skinned woman reading a letter 'To every Evora customer'); (b) green-screen grey-haired female narrator over luxury-location photos with yellow/white caption ('I stayed at the Burj Al Arab in Dubai', 'The richest family in American history', 'The family I nanny for has eight crew on their boat')")),
 (r"try evora riskfree|prueba evora", A("Direct offer / risk reversal", "Get the oil at half price without risk", "None (offer-only)", "Light: 'Six cold-pressed botanicals', 'Velvety, not greasy'", "'50% off until midnight tonight', 90-day risk-free, '50,000+ happy customers'", "Most-aware (retargeting-style)", "Midnight deadline 50% off + 90-day risk-free trial", "No story — bullet list + deadline", "Image viewed for 1361129475914444: 'Almost sold out… Restock in 2 months' — cartoon bottle mascot running ahead of a crowd of women")),
 (r"secret inside a wealthy|secreto dentro|skincare secret of a wealthy|skincare secret his mother|what happened on that (yacht|island)", A("Wealthy-household insider confession", "Have what rich, ageless women secretly use — for ~$40", "Narrator (56-64) has thin/papery/crepey arms; rich employer at 70+ has 'arms of a woman twenty years younger'", WAT + " (revealed mid-story)", "Arms/skin like the wealthy woman's; 'Say goodbye to crepey, saggy & dry skin... results in 3–4 weeks — or get your money back' (link description)", "Unaware → problem-aware (curiosity entry; product revealed late)", "Among all the luxury in a billionaire's home, the one thing worth copying is a ~$40 amber pump bottle of body oil", "Long-form first-person advertorial (8-11k chars): forbidden-confession opener ('I'm going to lose this job / get fired for posting this') → 'Let me rewind' → narrator age & job → luxury inventory with dollar figures → minimalist bathroom shelf (one amber pump bottle) → narrator tries it → spouse/others notice → mechanism → offer", "Image viewed for 1476760844282623: people jumping off a superyacht; 1021976634228403: selfie-style narrator inset over first-class cabin with kids, caption 'I'm a nanny for a family in New York' — native/UGC, product not shown")),
 (r"butler brought me|flight attendant brought me|weird ritual in our|not proud of what i took|weird oil in our|weird serum in our|odd oil in our cruise|odd oil i finish|spa owners personal oil|5800 retreat|french luxury skincare formulator|doesnt even use her own", A("Luxury-experience / professional-insider discovery ('the weird oil in the bathroom')", "Feel like the pampered woman in the five-star setting; arms that feel 'like mine again'", "Thin, papery, crepey arms/chest/hands after 50; lotions evaporate; hiding in sleeves", WAT, "Visibly firmer/smoother arms; strangers/husband notice; 90-day guarantee", "Unaware → problem-aware", "The most valuable thing from a five-star hotel / first-class flight / spa / cruise was a <$40 unbranded amber bottle of body oil", "Long-form first-person narrative: luxury setting with sensory/dollar detail → the 'weird'/'odd' bottle → emotional reaction (often a note/voicemail from a guest) → 'Let me rewind' → discovery of Evora → mechanism → offer", "Images viewed: 1788648425514311 Ritz Paris street scene with caption text overlay; 857286387379018 Honolulu police SUV in front of hotel (curiosity, ties to 'stole a bottle'); 2329433507867811 women in robes in a sauna — native lifestyle photos, no product")),
 (r"biltmore|richest women in america|titanic", A("Historical-luxury artefact / 'what the richest family used'", "Use the same thing the Vanderbilts/first-class Titanic passengers used", "Modern watery lotions vs. old-world oil rituals; narrator's thin arms", "Pre-lotion era used oil after the bath; oil vs water-based lotion (" + WAT + ")", "Arms better than hers at 81 ('She answered her door in short sleeves'); ~$40 today", "Unaware", "The richest women in history oiled their skin after the bath — one bottle today feels exactly like it", "First-person tour-guide / history-teacher narrative → historical luxury facts (43 bathrooms, Titanic auction) → question 'what did they put on their skin?' → lady's-maid descendant / artefact → Evora", "Image viewed for 1117655404344095: Biltmore Estate exterior photo (native, no product); 1450059447266329 thumbnail downloaded (not inspected in sheet)")),
 (r"14 drink|didnt recognize me at the airport|hates this oil", A("Spouse-jealousy / romance comedy", "Be seen and desired again; husband's renewed attention", "Hid in cover-ups/cardigans for years; arms went thin and papery around fifty", WAT, "'most beautiful skin on the beach'; wearing a swimsuit again", "Unaware → problem-aware", "A stranger complimented my skin in front of my husband — now he's ordering the bathroom body oil", "Opens on husband's punchline dialogue at dinner ('Let me get this straight...') → 'Let me rewind' → trip (Maui/Europe) → hotel-bathroom oil → transformation → product", "Image viewed for 2014827096140525: woman's bare shoulder holding a lei at Hawaii airport arrivals (native photo)")),
 (r"world cup|package has women waiting", A("Life-event / emotional (solo travel, widowhood) and delivery-driver social proof", "Reclaim a life of 'someday' plans; feel confident in sleeveless clothes", "Grief/self-neglect; hiding arms in cardigans", WAT + " (late in story)", "Confidence to go out and be seen", "Unaware", "A 60-year-old woman finally does the thing alone — and her skin is part of getting her life back / women are waiting at the door for this package", "Long-form personal essay with emotional arc → skin as sub-plot → product", "Image viewed for 882082784513664: POV from a delivery truck, woman with dog waiting at the end of a rural driveway (native photo)")),
 (r"why most body lotions|dont absorb this oil can|almost given up on my skin|this oil changed everything", A("Mechanism-led problem/solution", "Finally something that works on crepey arms/papery chest/hands", "'most body firming lotion and creams don't actually work' — 70-80% water, evaporate, never reach deeper layer", WAT + "; named oils: Wakame Algae, Brazil Nut, Passionflower Seed, Rice Bran (+ argan, vitamin E)", "Results by week six / 'two minutes a day'; full refund if no change", "Problem-aware / solution-aware", "Lotions are mostly water — an oil that matches the skin's lipid barrier reaches where creams can't", "Short direct-response (≈400-1,500 chars): call-out/question → reason-why → named ingredients → bullets → guarantee", "Image viewed for 1934644087249957: 'NATURAL BOTOX IN A BOTTLE?' product-callout graphic (Smooths crepey skin / Rebuilds the lipid barrier / Firmer arms / Trusted by thousands of women over 50 / Absorbs in seconds / Developed by dermatologists / 'NOW 50% OFF'); 1808170097172717 video thumb: stylised blue woman reading letter 'To every Evora customer'")),
 (r"paid full price", A("Sale announcement disguised as customer regret", "Get it cheaper ('64% in total')", "'I want Evora… but I can't afford it.' (price objection)", "Light: 'six oils... replace a lipid your skin stopped making after menopause' in some variants", "Visibly smoother skin; 90-day MBG", "Most-aware", "Holiday sale (Labor Day 50% + code LABOR64) framed as 'I paid full price — now it's on sale 😭'", "Short: objection quote → 'We heard you' → stacked discount → bullets → link", "Image thumbnail for 933885069780904 downloaded; not inspected")),
 (r"which body oil ranked", A("Third-party comparison / 'ranked #1'", "Pick the objectively best oil without wasting money", "Many body oils for crepey/dry skin — which works?", "Editorial reasoning (water-free base, absorption, actives) on landing page", "'One formula clearly stood above the rest... costing significantly less per bottle'", "Solution-aware (comparing options)", "Side-by-side review of the top 5 body oils for crepey skin — one clear winner", "Short teaser → fake-editorial listicle", "Image viewed for 1592473439201348: 'READ THIS BEFORE BUYING CREPEY SKIN BODY OILS' — five legs with five bottles over a red-to-green BAD→EXCELLENT scale, 'VIEW THE RANKINGS →'")),
 (r"look at that nice", A("Product beauty shot", "Aesthetic/desire for the object", "None", "None", "None", "Most-aware", "Product hero image", "Single-line caption", "Image viewed for 1310393507346261: clear glass bottle with golden oil and white pump on a bathroom vanity")),
]
COMP = {  # by brand -> default annotation; per-ad overrides below
 "Goda": A("Testimonial transformation ('I was doing it all wrong')", "Firm, silky skin; wear sleeveless again", "'Dryness, saggy and crepey skin'; creams moisturise for hours then back to 'paper-thin, crepey texture'", "'creams sit on top of the skin, but oils penetrate deep where the real problems start'; '7 cold-pressed oils that work at different levels of the skin'", "Crepey texture smoothing 'within weeks'; firmer, silky smooth", "Problem-aware", "An aesthetician's tip: switch from creams to a penetrating body oil", "Quoted customer testimonial ('Michelle D.') → aesthetician reveal → skepticism (greasy?) → results timeline → P.S. daughter steals it → CTA", "Image viewed for 1074806978599949: split before/after of a grey-haired woman's back/arm ('BEFORE GODA' / '2 WEEKS ON GODA') with bottle and '50% OFF' badge; 4109833019265205: 'THE #1 CHOICE FOR BODY OIL — I'm 55 and don't expect miracles… But this one is pretty close.' + 5 stars, 'WITH OVER 50,000+ 5-STAR REVIEWS'"),
 "NØRD BODY": A("Body-confidence call-out (shorts/cellulite/crepey)", "Feel confident in shorts/sleeveless without hiding", "'Ever avoid wearing shorts because of sagging or creepy skin?'", "Peptide body oil (copper peptides, caffeine, CoQ10 in some variants); 'oil penetrates better than ~80% water creams'", "Smooth, firm skin; money-back/60-day guarantee", "Problem-aware", "Peptides — proven on faces — now in a fast-absorbing body oil", "Short call-out → promise → CTA; advertorial landing carries the argument", "Image viewed for 1637558804018844: handwritten 'Rebuilds Collagen In 4 Weeks' on a thigh next to the pump bottle"),
 "VitaeCharm": A("Niche-trigger mechanism (GLP-1 weight loss / bruising / cancer survivors)", "Thicker, less fragile, firmer skin", "Crepey/deflated skin after GLP-1; easy bruising after 50; radiation-damaged skin", "'fat cushion layer' depleted; GLA + palmitoleic acid; 'penetrates 5 layers deep'; water-based creams can't rebuild", "Skin restored 'in as little as 8 weeks'; 90-day MBG", "Problem-aware (specific sub-segment)", "Your skin didn't age — the fat cushion beneath it collapsed", "Reason-why long copy: 'This Is Why' headline → cause → why creams failed → two specific nutrients → offer", "Image viewed for 1048726737582951: close-up of oiled crepey forearm with caption 'stop using coconut oil for Ozempic skin anymore'"),
 "Besque": A("Offer / value (XL bottle, 35% off subscription) + persona-page stories", "Keep using a loved oil for less; firm skin in 50s+", "Running out / price; crepey arms, post-GLP-1 skin (persona page)", "'Seven unrefined cold pressed oils'", "Luminous, firm, ultra-hydrated skin; '500,000+ women'", "Most-aware (brand page) / problem-aware (persona page)", "Twice the oil, 35% cheaper", "Short offer copy (brand page); first-person family story (40 Plus & Fabulous)", "Image viewed for 3912945868841510: 'The World's No.1 Body Oil — EXCLUSIVE OFFER', Trustpilot 4.8/5 with 9,000+ reviews, $120.00 struck → $78.00, 35% OFF"),
 "DRMTLGY": A("Dermatologist-developed retinol body lotion", "Firmer, smoother skin 'from the neck down'", "Crepey skin, loss of elasticity, uneven tone", "Gentle retinol + shea butter + ceramides", "Improved elasticity, reduced look of crepey skin; risk-free", "Solution-aware", "Face-grade retinol for the body", "Short feature-benefit bullets (DCO catalogue format)", "not viewed"),
 "Feline Skinscience": A("Myth-busting ('The Crepey Skin Myth')", "Firm, youthful neck/arms", "'At 48, my neck and arms looked like crepe paper'", "'Dr. Turner's moisturizing method'", "Restores youthful texture; free delivery", "Problem-aware", "The real reason crepey skin happens (myth series template reused across concerns)", "Testimonial quote → offer bullets", "Image viewed for 4092537667704644: 'Real Results. Real Renewal. 21.7% Reduction in visible crepiness in 7 days / 29.4% Improved skin elasticity in 14 days' with two jars"),
 "Miami MD": A("Harvard-dermatologist authority + named culprit", "Smooth crepey skin / lift sagging", "'There's a reason most creams aren't working'", "'Fibroblast Failure' → Ribose 'beauty sugar'; 'Progerin buildup' (Lift & Firm)", "Smooth away crepey skin; risk-free trial", "Problem-aware", "A named hidden cause that ordinary moisturisers can't fix", "Affiliate prelander/VSL/quiz funnels with doctor persona 'Dr. J'", "not viewed"),
 "OSEA": A("Clean-clinical seaweed body oil / value pack", "Firm, hydrated, great-smelling skin", "Mature skin elasticity", "Seaweed (Undaria algae) 'clinically tested to visibly improve elasticity'", "Visibly firms, smooths; 'Holy grail for mature skin'", "Most-aware / solution-aware", "The ocean's secret for firmer skin — #1 bestseller", "Short brand copy + discount", "Image viewed for 1085399840700489: 'Double The Citrus Bliss' jumbo pump bottle with orange and mango, 'SAVE 16%'"),
 "Saeskyn": A("K-beauty multi-tasker / pharmaceutical claim", "Look 10 years younger fast; simplify routine", "Wrinkles, crepey neck, sagging", "Fermented Jeju oils, salmon DNA, PDRN, peptides", "'Erases fine lines in hours', '94% saw firmer skin in 4 weeks'", "Solution-aware", "Korean innovation that replaces 6 products / pharmaceutical science", "POV list / skeptic-turned-believer short copy", "Video thumbnail viewed for 2032403464184564: close-up of glowing face, caption 'In 8 day?'"),
 "TurmSkin": A("Deadline sale (BOGO-stack)", "Hydrated, firmer, younger-looking skin", "Fine lines, crepey skin, dullness", "Triple hyaluronic acid + Matrixyl + Argireline, 'DeepCell Hydration Technology™'", "Plumper, firmer 'from day one'", "Most-aware", "Biggest sale — Buy 2 Get 4 FREE until midnight", "Short promo copy → listicle", "Video thumbnail viewed for 1998108007419317: hand holding serum box, 'NEW YEAR SALE ENDS SOON!', 'BUY 2 GET 4 FREE'"),
 "Frøya Organics": A("Natural Arctic-botanical balm via blogger persona", "Visible anti-ageing results fast without toxins", "Dry, red, flaky, wrinkling skin; retinol 'thins your skin'", "Arctic herbs survived brutal cold so are nutrient-dense", "Results 'in DAYS', 'Two Weeks. Brand New Skin.'", "Problem-aware", "Little Arctic anti-age secret", "First-person testimonial / customer-letter stories from 'Anne's Skincare Blog' page", "Image viewed for 1205891440980813: macro of amber balm texture, caption 'no water fillers'"),
 "emilycarterblog.com": A("Comparison 'scam' exposé", "Stop wasting money; find the one cream that works", "'stopped wearing sleeveless tops because of crepey, sagging skin'", "Peptides/niacinamide % disclosure on landing", "'which crepey skin cream actually delivered'", "Solution-aware (has tried Gold Bond, Crêpe Erase, StriVectin, Miami MD)", "I tested 5 crepey-skin creams head-to-head — 4 failed", "Teaser → fake-editorial comparison (winner: Cellu Deep Firming Body Cream)", "Image viewed for 971890085912295: sign 'THE BEST AND WORST CREPEY SKIN PRODUCTS' above Miami MD, Crepey Skin Repair Cream, Body Firm, Gold Bond packs"),
 "theskinmag.com": A("Sibling comparison / failed-gadget confession", "Arms that look 10 years younger", "Dermatologist-prescribed cream left arms raw; $1,400 of unused devices", "'one ingredient... never retinol' (copper peptide, 1973 discovery on landing)", "Younger-looking arms", "Solution-aware (tried retinol, devices)", "The 1973 Nobel-prize discovery that explains why nothing worked", "Short hook → curiosity gap → fake-news advertorial", "Video thumbnail viewed for 1720931215870603: two forearms side by side, captions 'Her arm. My arm. MY CREPEY ARMS AT 61.' / 'My sister Vicki is 4 years older than me'"),
 "Beekman 1802": A("Post-weight-loss firming", "Firm skin after weight loss", "'rapid weight loss has left your skin looking loose or crepey'", "Goat milk exosomes, COLLAGEN++", "Better-aging prescription", "Problem-aware", "Firm skin after weight loss", "One-liner (DCO)", "not viewed"),
 "Beauty From Bees": A("Natural waterless body serum discount", "Relief from tight, flaky, itchy skin", "Dry body skin", "'100% natural, waterless', 7 ingredients", "Feel relief", "Problem-aware", "Waterless 7-ingredient body serum", "Short call-out + code", "not viewed"),
 "Remedy Skin": A("Dermatologist-creator clinical stat", "Smoother neck/chest", "Crepey neck texture", "Encapsulated retinaldehyde + peptides", "'93% saw smoother-looking neck skin after 4 weeks'", "Solution-aware", "Dermatologist-developed serum stick", "Short clinical copy", "not viewed"),
 "tryorgatics.com": A("Rogue-doctor confession (supplement)", "Fix crepey, thinning skin from inside", "Creams/lasers fail on crepey, thinning skin", "Inside-out softgels", "Implied", "Problem-aware", "A dermatologist breaks down after her own laser — the inside-out fix", "Profane pattern-interrupt opener → dramatic personal story", "not viewed"),
 "": A("Fake-consumer question 'seeding' (text-only, no link)", "Find a body serum that works on crepey arms", "'my esthetician said i need a hyaluronic acid body serum for my crepey arms'", "Hyaluronic acid (named in question)", "None", "Problem-aware", "Organic-looking question post to trigger comment recommendations", "Single lowercase question, no CTA", "Text-only"),
}

OVR = {
 "4351937398417845": dict(angle="Perfume attraction claim (Goda For Her) — off-category copy", desire="Be irresistible / compliments", problem_framing="None (scent)", mechanism="'Synergizes with your natural scent'", promise_claim="'compliment-magnet'", awareness_level="Unaware", big_idea="2 drops change your life", story_structure="Quote + 3 ticks", visual_default="not viewed"),
 "1183652923933432": dict(angle="'The lotion lie' — seasonal (winter) dryness", desire="Comfortable, uncracked winter skin", problem_framing="At 56 after menopause legs crack and bleed, arms 'sandpaper', $40-50/month on body butters", mechanism="More lotion ≠ fix (oil vs lotion)", problem2="", promise_claim="Skin surviving winter", awareness_level="Problem-aware", big_idea="Winter skin isn't a moisture problem — it's the lotion lie", story_structure="First-person confession → years of failure → reframe → product"),
 "1070866808556946": dict(angle="Identity / future-self aspiration", desire="'wears what she wants' — no sleeve-pulling, tank tops in summer", problem_framing="Analyzing arms in every mirror, pulling sleeves down in photos", mechanism="'5 botanical oils that penetrate deep, trigger collagen'", promise_claim="Visibly smoother texture (timeline bullets)", awareness_level="Problem-aware", big_idea="This is who you become when your skin matches how vibrant you feel", story_structure="'She doesn't…' anaphora → transformation → ingredients → 'Women report' ticks"),
 "965929252430847": dict(angle="Cause-explainer ('nothing to do with just getting older')", desire="Firmer neck and arms in 30 days", problem_framing="Thin crinkled crepe-paper texture on neck/arms/legs; told it's 'just aging'", mechanism="Structural cause explanation (education page goda.co/pages/crepey-skin)", promise_claim="'Firmer neck and arms in 30 days'", awareness_level="Problem-aware", big_idea="Why your skin suddenly looks crepey — and it isn't age", story_structure="'Let me be direct' long-form explainer → bridge to page"),
 "865686186087862": dict(angle="Dermatologist explains TEWL", desire="Hydrated, less fragile mature skin", problem_framing="Mature skin turns dry, wrinkly, fragile", mechanism="Trans-epidermal water loss (TEWL) explained by a dermatologist", promise_claim="From crepey to radiant", awareness_level="Problem-aware", big_idea="The #1 physiological reason mature skin turns dry", story_structure="Authority explainer → page goda.co/pages/crepey-skin-tewl"),
 "1175006387786014": dict(angle="Lotion-vs-oil realisation testimonial", story_structure="Quoted testimonial ('I used to think lotions were enough…') → oil reveal → CTA"),
 "867230179084122": dict(angle="Black Friday sale wrapper on the testimonial", awareness_level="Most-aware / problem-aware", big_idea="'Goda’s Black Friday Sale makes NO sense!' + Michelle D. testimonial"),
 "2455348678278754": dict(angle="Menopause skin-change education", problem_framing="'Menopause-related skin changes... thinner, looser or more crepey-looking'", mechanism="Copper peptides, caffeine, CoQ10; 5–10 minute massage ritual", promise_claim="'Skin looks softer in approximately 4 weeks, with visible firming...'", awareness_level="Problem-aware", big_idea="Moisture alone isn't the answer to crepey menopausal skin"),
 "1378620250383895": dict(angle="Husband-noticed side benefit (bought for arms, legs changed)", desire="Smoother legs/arms; spouse notices", story_structure="Testimonial: bought for arms → husband notices legs → peptide mechanism → result"),
 "1341132271434598": dict(angle="Skeptic testimonial + guarantee", story_structure="'I thought here we go again…' → modest result ('still have older hands... best in years') → 60-day guarantee"),
 "968648789592742": dict(angle="Quiz funnel (no primary text)", desire="", problem_framing="", mechanism="", promise_claim="", big_idea="Personalised quiz entry", story_structure="Video only, no copy"),
 "2521217498380442": dict(angle="Body-confidence call-out — cellulite variant", problem_framing="'Ever avoid wearing shorts because of cellulite?'"),
 "1611807499919232": dict(angle="Body-confidence call-out — cellulite variant", problem_framing="'Ever avoid wearing shorts because of cellulite?'"),
 "1811884486444866": dict(angle="Body-confidence call-out — sleeveless/crepey variant", problem_framing="'Ever avoid wearing sleeveless tops because of crepey skin?'"),
 "1078737738359846": dict(angle="Persona family-event story (mother-of-the-bride, sleeveless dress)", desire="Not be outshone in the sleeveless mothers' photo", problem_framing="61-year-old widow vs. 58-year-old tennis-armed co-mother; 'Why crepey arms come back every afternoon'", awareness_level="Unaware → problem-aware", big_idea="Same sleeveless dress, two very different arms", story_structure="Long-form first-person social-comparison story (persona page '40 Plus & Fabulous')"),
 "1609139254186765": dict(angle="Post-GLP-1 skin (persona page)", problem_framing="'You lost the weight - so why are you still hiding your arms, stomach and thighs?'", mechanism="'Body oiling naturally reverses the effects GLP-1 weight loss has on skin'", awareness_level="Problem-aware (GLP-1 users)", big_idea="Weight's gone — the skin needs catching up"),
 "1113341161654036": dict(angle="Post-weight-loss 'new chapter' + discount (persona page)", problem_framing="Skin after weight loss", promise_claim="'Helps improve the appearance of crepey skin'", big_idea="Anti-Sag Formula now 35% off"),
 "1714552492862170": dict(angle="Off-category (face sunscreen + eye corrector duo)", desire="Quick glowing routine", problem_framing="None", mechanism="None", promise_claim="Smooth, radiant skin", big_idea="Minimalist makeup duo", story_structure="Short promo"),
 "1101365469083009": dict(story_structure="'For YEARS I was frustrated…' first-person myth-busting → offer (10 IDs in sample from 2026-09-07)"),
}

def norm(t): return re.sub(r'[^a-z0-9 ]', '', (t or '').lower().replace('’', "'"))
def evora_ann(r):
    k = norm(r["eff_title"]) + " " + norm((r["eff_body"] or "")[:200])
    for pat, a in EVORA:
        if re.search(pat, k): return a
    return A("unclassified", "", "", "", "", "", "", "", "")
def status(r):
    e = r.get("end_date") or ""
    if e >= "2026-10-02": return f"ACTIVE (library end_date {e} = still delivering)"
    return f"listed active but last delivery {e} (likely paused/stopped)"
def ev_strength(r):
    ids, pages, col, d = r["concept_ids_in_sample"], len(r["concept_pages_in_sample"]), r["concept_collation_sum"], r["days_running"] or 0
    live = (r.get("end_date") or "") >= "2026-10-02"
    sig = []
    if d >= 60: sig.append(f"longevity {d}d")
    if ids >= 10: sig.append(f"concept replicated in {ids} ad IDs")
    if pages >= 2: sig.append(f"cross-page ({pages} pages)")
    if (r.get("collation_count") or 1) >= 3: sig.append(f"{r['collation_count']} ads use this creative")
    if live: sig.append("still live")
    long_ = d >= 60
    other = len([s for s in sig if not s.startswith(("still", "longevity"))])
    if long_ and other >= 1: lvl = "HIGH" if live else f"HIGH-historical (now stopped; last delivery {r.get('end_date')})"
    elif other >= 3 and live: lvl = "HIGH (concept-level; this ad ID is <60d)"
    elif (long_ or other >= 1) and live: lvl = "MEDIUM"
    elif long_ or other >= 2: lvl = "MEDIUM (not currently delivering)"
    else: lvl = "LOW"
    return f"{lvl}: " + ("; ".join(sig) if sig else "single observation") + f" [concept: {ids} IDs / {pages} page(s) / collation sum {col} in our sample]"
def first_line(b):
    for l in (b or "").split("\n"):
        l = l.strip().strip("⠀").strip()
        if l: return l
    return ""
def excerpt(b, n=320):
    b = (b or "").replace("\r", "")
    return b if len(b) <= n else b[:n] + " [...]"
rows = [json.loads(l) for l in open(D + "/raw/_ledger_selection.jsonl")]
order = {"Evora Body": 0, "Evora Body (via skinglowmagazine listicle)": 1}
rows.sort(key=lambda r: (order.get(r["brand"], 2), r["brand"], r["page_name"], r["start_date"]))
cols = ["ad_id","source","page_name","brand/domain","status","start_date","days_running","variant_count","format","hook","headline","body_excerpt","angle","desire","problem_framing","mechanism","promise_claim","awareness_level","big_idea","story_structure","cta_offer","visual_pattern","landing_url","landing_page_pattern","evidence_strength","notes"]
with open(D + "/swipe_ledger.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols); w.writeheader()
    for r in rows:
        isev = r["domain"] in ("evorabody.com", "skinglowmagazine.com")
        a = dict(evora_ann(r) if isev else COMP.get(r["brand"], COMP[""]))
        if r["ad_archive_id"] in OVR: a.update({k: v for k, v in OVR[r["ad_archive_id"]].items() if k in a})
        vis = a["visual_default"] or ""
        fmt = r["display_format"] or "unknown"
        if r["ad_archive_id"] in vis: vis = f"[{fmt}] THIS AD VIEWED. " + vis
        elif r["ad_archive_id"] in VIEWED: vis = f"[{fmt}] thumbnail downloaded (thumbs/{r['ad_archive_id']}.jpg) but not individually described. Concept examples: " + (vis or "n/a")
        elif vis and vis not in ("not viewed", "Text-only"): vis = f"[{fmt}] This ad not viewed. Concept examples viewed: " + vis
        else: vis = f"[{fmt}] not viewed" if vis != "Text-only" else "Text-only (no media)"
        ld = (r.get("link_description") or "").strip()
        if "{{" in ld: ld = ""
        cta = f"CTA button: {r.get('cta_text') or 'none'}" + (f" | link description: {ld}" if ld else "")
        brand = r["brand"] or "unknown (no landing URL)"
        notes = []
        if r["display_format"] == "DCO": notes.append("DCO ad: copy taken from first dynamic card")
        if "es.evorabody" in r["eff_link"] or "/es/" in r["eff_link"]: notes.append("Spanish-language variant for US Hispanic audience")
        if r["page_name"] not in ("Evora Body",) and isev: notes.append(f"Persona/advertorial page linking to {r['domain']}")
        if r["brand"] == "Goda" and r["page_name"] != "Goda Perfume": notes.append("Goda persona page")
        if r["page_name"] == "Joanna Woodley": notes.append("Advertiser/brand not identifiable from library record (no link); 75 active ads on this page per library count")
        notes.append(f"days_since_start_asof_2026-10-03={r['days_since_start_asof_2026-10-03']}; surfaced by: {', '.join(sorted(set(r['sources'])))}")
        w.writerow({"ad_id": r["ad_archive_id"], "source": "Meta Ad Library (US, public, logged-out)", "page_name": r["page_name"].strip(),
            "brand/domain": f"{brand} / {r['domain'] or '-'}", "status": status(r), "start_date": r["start_date"],
            "days_running": r["days_running"], "variant_count": f"{r.get('collation_count') or 1} (library 'ads use this creative'); concept IDs in sample: {r['concept_ids_in_sample']} across {len(r['concept_pages_in_sample'])} page(s)",
            "format": r["display_format"], "hook": first_line(r["eff_body"]) or "(no primary text)", "headline": r["eff_title"] or "(none)",
            "body_excerpt": excerpt(r["eff_body"]), "angle": a["angle"], "desire": a["desire"], "problem_framing": a["problem_framing"],
            "mechanism": a["mechanism"], "promise_claim": a["promise_claim"], "awareness_level": a["awareness_level"], "big_idea": a["big_idea"],
            "story_structure": a["story_structure"], "cta_offer": cta, "visual_pattern": vis, "landing_url": r["eff_link"],
            "landing_page_pattern": lp(r["eff_link"]), "evidence_strength": ev_strength(r), "notes": " | ".join(notes)})
print("rows", len(rows))
