import json, re, glob, collections
import xml.etree.ElementTree as ET
S='/tmp/claude-0/-home-user-Shop-aufbau/5b2336da-6c1e-5391-be3e-77204cb3c276/scratchpad'
NS={'a':'http://www.w3.org/2005/Atom'}
G=json.load(open(S+'/gen_out.json'))
rows,excl=G['rows'],G['excl']
def esc(s): return str(s).replace('|','\\|').replace('\n',' ')
# backlog titles
titles={}
for line in open('/home/user/Shop-aufbau/falunara-research/voc/voc1_raw_search_hits.md',encoding='utf-8'):
    m=re.match(r'^- \[(.*?)\] (\S+) — (.*) — (https://\S+)',line)
    if m:
        i=m.group(4).split('/comments/')[1].split('/')[0]; titles.setdefault(i,(m.group(3),m.group(2),'VOC1 raw hits'))
for f in glob.glob(S+'/search/*.xml'):
    for e in ET.parse(f).getroot().findall('a:entry',NS):
        u=e.find('a:link',NS).get('href'); i=u.split('/comments/')[1].split('/')[0]
        titles.setdefault(i,(e.find('a:title',NS).text,e.find('a:updated',NS).text[:10],'VOC2 search'))
cached=set(open(S+'/cached.txt').read().split())
back=[]
seen=set()
for l in open(S+'/allcand.tsv'):
    i,sub,url,src=l.rstrip('\n').split('\t')
    if i in cached or i in seen: continue
    seen.add(i); t,d,s=titles[i]; back.append((sub,i,t,url,d,s))
ORDER=['40PlusSkinCare','45PlusSkincare','30PlusSkinCare','Menopause','Perimenopause','SkincareAddiction','SkincareAddicts','Skincare_Addiction','beauty','AskWomenOver40','AskWomenOver30','Sephora','Ulta','TwoXChromosomes','tretinoin','AskOldPeople','xxfitness','AskDocs']
back.sort(key=lambda x:(ORDER.index(x[0]) if x[0] in ORDER else 99,x[4]))
inc_c=collections.Counter(r['Community'] for r in rows)
exc_c=collections.Counter(('r/'+e['sub']) if e['sub']!='Inspire' else e.get('community','Inspire') for e in excl)
back_c=collections.Counter('r/'+b[0] for b in back)
score_c=collections.Counter(r['Quality score'] for r in rows)
L=[]
A=L.append
A('# VOC Prompt 2 — Reddit / Forum URL Corpus')
A('**Product:** FALUNARA Botanical Body Oil · **Market:** U.S. · **Target:** U.S. women 40–65+ (core 48–58) with dry, crepey-looking mature body skin (menopause = context only)')
A('**Date built:** 2026-10-03 · **Input:** `VOC1_Community_Map.md` + `voc1_raw_search_hits.md` · **Status:** URL corpus only — no VOC conclusions drawn. Required input for VOC Prompt 3 (this FALUNARA run only).')
A('')
A(f'**Result:** {len(rows)} verified, included threads (`VOC2_URL_Corpus.csv`) · {len(excl)} opened-and-excluded/flagged threads · {len(back)} unverified backlog candidates (not opened, not scored).')
A('')
A('---')
A('')
A('## 1. Method (what was actually done)')
A('')
A('1. **Seed selection from VOC1.** All 944 VOC1 discovery rows (937 unique thread IDs) were screened by title against the VOC1 filter rules (body area is the subject; drop eye/eyelid/face-only "crepey"; drop weight-loss loose skin unless texture is described; drop UK communities). 152 seed candidates were taken forward, following VOC1 tier order (r/40PlusSkinCare → r/30PlusSkinCare → r/Menopause → r/SkincareAddiction → Tier 2 → Tier 3 spot-checks).')
A('2. **Supplementary searches (26 queries, VOC1 query families).** Reddit in-sub search RSS (`/r/<sub>/search.rss?q=…&restrict_sr=1&sort=relevance&t=all&limit=25`) for: r/40PlusSkinCare (crepey arms, crepey hands, body oil, dry legs, menopause skin body, crepe corrector, urea lotion, body lotion, lactic acid body), r/30PlusSkinCare (crepey arms, rest of my body, body after 50), r/Menopause (body lotion, crepey arms, skin changes body, body oil skin), r/Perimenopause (body skin, body lotion), r/SkincareAddiction (crepey arms legs, body oil 50), r/AskWomenOver40 (skin body), r/beauty (turning 50 body, crepey arms) and **r/45PlusSkincare** (crepey, body, body oil).')
A('   - **New community found:** r/45PlusSkincare is not in the VOC1 map; it is named in r/40PlusSkinCare\'s own sidebar as a sibling age-specific sub. Its searches returned the densest on-target body/crepey threads of any query, so it was treated as Tier-1-equivalent (age-gated 45+). 86 additional candidates came from these searches.')
A('3. **Verification — every scored thread was opened.** Each candidate was fetched as thread RSS (`https://www.reddit.com/r/<sub>/comments/<id>/.rss?limit=100`) with curl (`-A \'Mozilla/5.0 (X11; Linux x86_64) research\'`), ≥7–14 s between requests, 55–120 s back-off on HTTP 429. 151 thread fetches succeeded (plus 1 test fetch); 86 HTTP 429 responses were absorbed by back-off (shared IP). For every opened thread the OP text and comments were parsed; counted: comments retrieved, first-person pronoun density, body-area term frequency, stated ages, U.S./UK retail/spelling signals; OP and leading replies were read manually before scoring.')
A('4. **Off-Reddit (optional):** Inspire.com menopause groups fetched with curl + browser UA (HTTP 200). Inspire\'s site search is JavaScript-only, so additional threads were discovered via WebSearch (`allowed_domains: inspire.com`). 5 threads opened; 2 included. Mumsnet / r/SkincareAddictionUK excluded as non-U.S. per brief; other forums were inaccessible per VOC1.')
A('5. **Cache for VOC Prompt 3:** every opened thread is saved verbatim at `falunara-research/voc/thread_cache/<thread_id>.xml` (Reddit Atom, up to 100 entries = OP + comments) and `thread_cache/inspire_<slug>.html` (Inspire). VOC Prompt 3 should extract from these files so the text is identical to what was scored (mapping in §8).')
A('6. **Fields:** Thread title = verbatim Reddit/Inspire title from the opened feed/page. URL = canonical link of the OP entry in the thread feed (`https://www.reddit.com/r/<sub>/comments/<id>/<slug>/`). Date = OP `<published>` timestamp (YYYY-MM-DD).')
A('')
A('## 2. Quality-score rubric (1–5)')
A('')
A('Five criteria, judged on the opened thread:')
A('')
A('| Criterion | High | Medium | Low |')
A('|---|---|---|---|')
A('| **Substance / comment volume retrieved** | ≥40 substantive comments | 10–39 comments | <10 comments, or mostly one-liners / automod |')
A('| **First-person depth** | Personal onset stories, routines, results, feelings | Mix of experience + generic advice | Mostly generic advice / links |')
A('| **Body-skin relevance** | Arms, legs/shins, knees, thighs, hands, chest/décolleté, belly, "all over" are the subject | Neck (body-adjacent) or body + face mixed | Face/eye-only (excluded unless clearly transferable and labeled) |')
A('| **Target-age fit** | Age-gated sub (40+/45+) or stated ages ~40–65+; menopause/peri context | Ages unstated in an older-skewing sub | Stated ages <35 or young-skewing thread |')
A('| **VOC richness** | Covers ≥4 VOC categories (problem, emotion, outcomes, solutions, objections, routines, purchase criteria) | 2–3 categories | 1 category |')
A('')
A('- **5** = high on ≥4 criteria, including body relevance and substance.')
A('- **4** = high on 3 criteria with no "low" (age-unstated counts as medium).')
A('- **3** = meets inclusion, with one notable weakness (moderate volume; neck/body-adjacent; facial-dominant but transferable; younger skew; or OP-depth carrying a thin thread).')
A('- **2** = thin or marginal → excluded/flagged (listed in §5).')
A('- **1** = empty/removed, off-topic, spam or marketer-written → excluded.')
A('')
A('**Inclusion rule:** score ≥3. Two documented exceptions to the ≥10-comment norm are included on OP depth: `1qfgegt` (7 replies; detailed 50-year-old purchase-criteria OP) and the Inspire "Skin sagging…" thread (2 replies; ~400-word first-person OP, age 54). To keep the corpus focused (~90), five verified score-3 threads that were facial-dominant or tangential were moved to a "reserve — below cut" list in §5.')
A('')
A('**VOC category legend used in the table:** Problem description · Emotional impact · Desired outcomes · Attempted solutions / product experiences · Objections / side effects / skepticism · Routines / application habits · Purchase criteria (texture, absorption, scent, price) · Age / menopause context.')
A('')
A(f'Score distribution (included): 5 = {score_c[5]}, 4 = {score_c[4]}, 3 = {score_c[3]}.')
A('')
A('## 3. Corpus table (included threads)')
A('')
F=['ID','Platform','Community','Thread title','URL','Date if available','Topic','Why relevant','Expected VOC categories','Quality score','Notes']
A('| '+' | '.join(F)+' |'); A('|'+'---|'*len(F))
for r in rows: A('| '+' | '.join(esc(r[f]) for f in F)+' |')
A('')
A('## 4. Community coverage counts')
A('')
A('| Community | Included | Opened & excluded/flagged | Unverified backlog |')
A('|---|---|---|---|')
comms=list(dict.fromkeys(list(inc_c)+list(exc_c)+list(back_c)))
for c in comms: A(f'| {c} | {inc_c.get(c,0)} | {exc_c.get(c,0)} | {back_c.get(c,0)} |')
A(f'| **Total** | **{len(rows)}** | **{len(excl)}** | **{len(back)}** |')
A('')
core=sum(v for k,v in inc_c.items() if k in ('r/40PlusSkinCare','r/45PlusSkincare','r/Menopause','r/Perimenopause','r/AskWomenOver40') or k.startswith('Inspire'))
A(f'- Age-gated 40+/45+ and menopause/peri communities: **{core} of {len(rows)}** included threads; r/30PlusSkinCare (40+/50+ posters common): {inc_c.get("r/30PlusSkinCare",0)}; general/retail/other subs: {len(rows)-core-inc_c.get("r/30PlusSkinCare",0)}.')
A('- Tier 2 SCA-family, r/beauty and retailer subs are under-represented relative to VOC1 targets because of rate limits late in the run (their candidates are in the backlog), and because several opened ones were thin.')
A('')
A('## 5. Opened but excluded / flagged (with reasons)')
A('')
A('| Thread ID | Community | Thread title | URL | Date | Score | Reason |')
A('|---|---|---|---|---|---|---|')
for e in sorted(excl,key=lambda e:(-e['score'],e['sub'])):
    comm=e.get('community') or 'r/'+e['sub']
    A(f"| {e['id']} | {comm} | {esc(e['title'])} | {e['url']} | {e['date']} | {e['score']} | {esc(e['notes'])} (comments retrieved: {e['ncom']}) |")
A('')
A('Exclusions applied before opening (not listed individually): eye/eyelid/face-only "crepey" titles, weight-loss loose-skin threads (r/loseit, r/xxfitness except spot-check), fragrance-only body-oil threads (r/fragrance), medical dermatitis (r/eczema, r/AskDocs), K-beauty archives (r/AsianBeauty), makeup subs, and all UK sources (r/SkincareAddictionUK, Mumsnet) as non-U.S.')
A('')
A('## 6. Unverified backlog (NOT opened, NOT scored)')
A('')
A('Candidates selected by title for relevance but not opened because of Reddit rate limiting (shared IP; ~1 fetch per 1–5 min in the final hour). Titles/dates are copied verbatim from the VOC1 raw hits or VOC2 search feeds. Verify before use.')
A('')
A('| Community | Thread ID | Title (from listing) | URL | Date (listing) | Source |')
A('|---|---|---|---|---|---|')
for sub,i,t,u,d,s in back: A(f'| r/{sub} | {i} | {esc(t)} | {u} | {d} | {s} |')
A('')
A('## 7. Limitations')
A('')
A('- **Rate limiting:** 86 HTTP 429s; the queue was reprioritized twice and stopped once the corpus reached ~90 verified threads. Remaining candidates are listed in §6, not scored.')
A('- **Comment depth:** Reddit thread RSS returns at most 100 entries (OP + ~99 comments) in feed order; deeper replies in large threads (100+ comments) are not retrieved. "Comments retrieved" in Notes is this retrieved count, not the thread total. Deleted comments appear as "[deleted]".')
A('- **U.S. residency cannot be verified** on Reddit. Signals noted where present (U.S. retailers such as Costco, Target, Walmart, CVS, Ulta, Trader Joe\'s; non-U.S. hints such as NHS, Canadian winters, NZ, Progynova/Primolut). All included communities are English-language and U.S.-dominant but international.')
A('- **Age** is only known when stated or implied by an age-gated sub; r/30PlusSkinCare, r/SkincareAddiction, r/beauty and r/Ulta threads skew younger and are labeled.')
A('- **Gender:** a few threads include male or gender-unstated posters (flagged; e.g. 17w7jhl). Male-OP threads were excluded.')
A('- **Menopause communities** are used as context; many replies are HRT/medical, and itch threads may reflect symptoms rather than cosmetic dryness — flagged in Notes.')
A('- **Brand seeding:** screened heuristically (brand-style usernames, explainer tone with no engagement, OP opening with a specific product endorsement, templated stats-heavy replies). Two threads were excluded on this basis (1t5c6ay, 1pu342w), one flagged (1u1zynn excluded), one included with a low-level flag (1vr68n7). Heavy AmLactin / Gold Bond enthusiasm across threads appears organic but should be weighed in VOC3.')
A('- **Quality scores** are analyst judgments on the rubric above, informed by automated counts; they are not inter-rater validated.')
A('- **Off-Reddit:** only Inspire.com was usable; Facebook groups, TikTok/YouTube comments and retailer reviews were out of scope/inaccessible.')
A('')
A('## 8. Handoff to VOC Prompt 3 — corpus ID → cached source file')
A('')
A('| ID | Cached file (under `falunara-research/voc/thread_cache/`) |')
A('|---|---|')
for r in rows:
    f=r['_id']+('.html' if r['_id'].startswith('inspire_') else '.xml')
    A(f"| {r['ID']} | `{f}` |")
open('/home/user/Shop-aufbau/falunara-research/voc/VOC2_URL_Corpus.md','w',encoding='utf-8').write('\n'.join(L)+'\n')
print(len(back),'backlog'); print(inc_c); print(exc_c)
