from engine import *

OILT = T('oil_on_damp_skin', 'oil_absorbs_fast', 'oil_greasy_staining', 'oil_seals_not_hydrates', 'oil_vs_lotion_confusion',
         'cheap_oil_alternative', 'competitor_body_oil', 'oil_shower_packaging_friction', 'natural_botanical_pref')

# ===================== 03 DESIRES =====================
DESIRES = [
 dict(name='Weiche, glatte, geschmeidige Haut (taktiles Ziel: „soft“, „smooth“, „supple“)',
      f=T('soft_smooth_desire'), ex=['A0017', 'B0252', 'B0307', 'C0165'], kind='direkt',
      note='Häufigstes positiv formuliertes Ziel; meist als erreichter Zustand in Erfolgsberichten beschrieben.'),
 dict(name='Schnell einziehen, nicht klebrig/fettig – sofort anziehen können',
      f=T('oil_absorbs_fast', 'sticky_film_texture', 'texture_weight_preference'), ex=['C0093', 'A0347', 'C0538', 'C0595'], kind='direkt',
      note='Kaufkriterium mit „Gatekeeper“-Funktion; eng verknüpft mit Objection fettig/Flecken.'),
 dict(name='Lang anhaltende Feuchtigkeit ohne ständiges Nachcremen',
      f=OR(T('lotion_temporary'), AND(C(DES, PUR, SUCC, TAC, PREF), RX(r"all day|24 hours|whole day|never need to reapply|lasts? (all|the)"))),
      ex=['A0358', 'C0269', 'C0194', 'C0092'], kind='direkt + abgeleitet',
      note='Überwiegend abgeleitet aus Klagen über kurzlebige Wirkung (lotion_temporary); direkte Wunschformulierungen seltener.'),
 dict(name='Arme/Beine wieder zeigen können (ärmellos, Shorts, Kleider) – Kleidungsfreiheit',
      f=T('confidence_desire', 'hiding_arms_sleeveless', 'shorts_dresses_avoidance'), ex=['B0804', 'A0782', 'B0100', 'A0148'], kind='direkt + abgeleitet',
      note='Teils aus Vermeidungsverhalten abgeleitet; Erfolgsmarker = wieder ärmellos tragen.'),
 dict(name='Bescheidenes Ziel: Prozess verlangsamen / nicht älter aussehen als ich bin',
      f=OR(RX(r"slow (it |this |the )?down|slowing|crepefication|older than I am|proactive"), AND(T('acceptance_aging'), C(DES))),
      ex=['C0353', 'C0460', 'A0321', 'A0142'], kind='direkt',
      note='Gegenpol zu „Reversal“-Erwartungen; viele Posterinnen wollen nicht „jung“, sondern „gepflegt/altersgemäß“.'),
 dict(name='Glow / gesunder Schimmer statt „ashy“/stumpf',
      f=T('glow_desire'), ex=['C0629', 'A0482', 'A0228', 'A0259'], kind='direkt',
      note='Deutlich seltener als soft/smooth; oft „Bonus“ in Erfolgsberichten.'),
 dict(name='Festigkeit / Elastizität / „bounce“ zurück',
      f=OR(T('firmness_desire'), AND(C(DES, QUE, PUR), RX(r"\bfirm|elastic|bounce|tighten|thicken"))),
      ex=['B0279', 'A0322', 'B0524', 'A0225'], kind='direkt',
      note='Wunsch existiert, wird aber häufig von der Skepsis begleitet, dass Topika das nicht leisten (siehe Objections).'),
 dict(name='Sich wieder wie „ich selbst“ fühlen / Identität zurück',
      f=T('feel_like_myself'), ex=['C0346', 'B0796', 'B0731', 'C0648'], kind='abgeleitet',
      note='Überwiegend aus Verlust-/Trauerformulierungen abgeleitet.'),
 dict(name='Wenige Schritte, einfache Routine',
      f=T('routine_fatigue'), ex=['A0673', 'A0749', 'C0039', 'B0786'], kind='abgeleitet',
      note='Abgeleitet aus Routine-Frust; C0039 ist ein direkter Wunsch nach kürzerer Post-Shower-Routine.'),
 dict(name='Angenehmer, dezenter Duft (Genuss, Parfum nicht „übertönen“)',
      f=T('scent_love'), ex=['C0497', 'C0535', 'A0407', 'C0291'], kind='direkt',
      note='Steht in direktem Widerspruch zum Wunsch nach Duftfreiheit (siehe Contradictions).'),
 dict(name='Duftfrei / sanft für empfindliche Haut',
      f=AND(T('fragrance_sensitivity'), C(PUR, PREF, QUE, DES)), ex=['A0643', 'C0269', 'C0251', 'B0149'], kind='direkt',
      note='Teilweise neue Duftunverträglichkeit in der Perimenopause (Kontext, keine Claims).'),
 dict(name='Linderung von Juckreiz, Schuppen, Spannungsgefühl (Komfort)',
      f=T('itch_flake'), ex=['A0018', 'C0367', 'C0250', 'A0670'], kind='abgeleitet',
      note='Abgeleitet aus Symptom-Schilderungen; Menopause-Threads mit medizinischer Überlappung.'),
 dict(name='Echte, nachvollziehbare Wirkung statt Hype („actually works“, transparente Dosierung)',
      f=OR(AND(T('marketing_distrust'), C(PUR, DES, PREF, QUE)), RX(r"genuinely|actually (work|help|moistur|improv)|\bhype")),
      ex=['A0005', 'A0272', 'A0617', 'C0533'], kind='direkt + abgeleitet',
      note='Positiv gewendete Form der Marketing-Skepsis.'),
 dict(name='Bezahlbarkeit / gutes Preis-Leistungs-Verhältnis',
      f=AND(T('price_value'), C(PUR, DES, PREF, SUCC, QUE)), ex=['A0750', 'B0258', 'B0126', 'A0019'], kind='direkt',
      note='Preisanker im Corpus meist ca. $10–30 für Körperprodukte (siehe Phrase/Objection bank).'),
 dict(name='Körperpflege als Ritual / Selbstfürsorge',
      f=T('self_care_ritual'), ex=['A0163', 'C0243', 'C0111', 'B0439'], kind='direkt',
      note='Kleinere, aber über viele Threads verteilte Stimme.'),
 dict(name='Dickere, widerstandsfähigere Haut (gegen „thin“, „see-through“, Blutergüsse)',
      f=T('thin_skin_bruising'), ex=['A0225', 'A0057', 'C0235', 'A0618'], kind='abgeleitet',
      note='Teilweise medizinische Überlappung (Blutergüsse, Schmerz).'),
]

# ===================== 04 PROBLEMS =====================
PROBLEMS = [
 dict(name='Crepey Oberarme/Unterarme', f=T('crepey_arms'), ex=['B0092', 'A0613', 'B0829', 'B0403'],
      ctx='Häufigste Körperzone; OP-Posts ab ca. 40–65, oft mit Vergleich zur Mutter oder mit „wings“-Spott der Familie.'),
 dict(name='Crepey/trockene Beine & Schienbeine („shins“)', f=OR(T('crepey_legs'), RX(r"\bshins?\b")), ex=['A0042', 'A0130', 'C0065', 'A0080'],
      ctx='Schienbeine als trockenste Zone; Shorts-/Rock-Vermeidung im Sommer.'),
 dict(name='Crepey Hände („granny hands“)', f=T('crepey_hands'), ex=['A0632', 'B0390', 'C0201', 'A0814'],
      ctx='Hände „älter als das Gesicht“; Altersflecken; HRT-Kontext in C006.'),
 dict(name='Haut über den Knien', f=T('crepey_knees'), ex=['A0108', 'A0176', 'C0396', 'A0321'],
      ctx='Kleinere Zone, aber konkret benannt; oft „woke up“-Narrativ.'),
 dict(name='Hals & Dekolleté (körpernah)', f=OR(T('crepey_chest'), AND(B('neck', 'chest'), C(PROB, SYM, EMO, IDN, PHR))), ex=['A0211', 'C0342', 'B0843', 'B0188'],
      ctx='Neck-Threads C016/C020–C022 dominieren; körpernah, aber teils face-adjacent.'),
 dict(name='Bauch/Oberschenkel: Erschlaffung, „saggy mush“, Elastizitätsverlust', f=OR(T('crepey_abdomen', 'firmness_desire'), AND(C(PROB, SYM, EMO), RX(r"sag|loose|saggy|lax|fluffy|jiggl"))),
      ex=['B0277', 'B0322', 'A0141', 'B0883'], ctx='Wird häufig mit Gewichtsverlust/GLP-1 und Training diskutiert.'),
 dict(name='Extreme Trockenheit, Juckreiz, Schuppen („body dandruff“)', f=T('itch_flake'), ex=['A0670', 'C0250', 'C0160', 'C0091'],
      ctx='Starke Symptomsprache v. a. in r/Menopause & Inspire; medizinische Überlappung möglich.'),
 dict(name='Dünne, durchscheinende, verletzliche Haut', f=T('thin_skin_bruising'), ex=['A0057', 'C0235', 'C0148', 'A0632'],
      ctx='Teils mit Schmerz/Blutergüssen; HRT-Kontext häufig.'),
 dict(name='Plötzlicher Beginn („overnight“, „woke up“)', f=T('sudden_onset'), ex=['B0020', 'B0390', 'A0099', 'B0358'],
      ctx='Schocknarrativ, Alter 40–65; zeitlicher Bezug oft „last few months“.'),
 dict(name='Alterungs-Identität: „old lady“, Mutter/Großmutter, Reptil-Metaphern', f=T('old_lady_identity', 'mothers_skin', 'texture_metaphor', 'invisibility_alienation'),
      ex=['B0865', 'A0716', 'B0829', 'C0007'], ctx='Haut als Marker eines ungewollten Identitätswechsels.'),
 dict(name='Verstecken & Kleidungsvermeidung', f=T('hiding_arms_sleeveless', 'shorts_dresses_avoidance'), ex=['A0080', 'B0089', 'C0636', 'B0806'],
      ctx='Lange Ärmel trotz Hitze; Shorts/Röcke über Knie vermieden.'),
 dict(name='Lotion wirkt nur kurz → ständiges Nachcremen', f=T('lotion_temporary'), ex=['C0194', 'B0088', 'C0092', 'B0356'],
      ctx='Gefühl, dass bisher funktionierende Pflege „nicht mehr reicht“.'),
 dict(name='Routine-Überforderung & -Müdigkeit (zu viele Schritte, Reihenfolge, Zeit)', f=OR(T('routine_fatigue'), AND(T('question_order_of_application'), C(QUE, FRIC))), ex=['A0749', 'A0673', 'C0034', 'B0087'],
      ctx='Körperroutine kommt zur Gesichtsroutine „oben drauf“.'),
 dict(name='Körper jahrelang vernachlässigt (vs. Gesicht)', f=T('body_neglect_vs_face', 'face_product_transfer'), ex=['A0001', 'C0256', 'C0445', 'C0422'],
      ctx='Gesicht gepflegt, Körper „vergessen“; Gesichts-Reste landen auf dem Körper.'),
 dict(name='Haut nach Gewichtsverlust / GLP-1', f=T('weight_loss_glp1'), ex=['B0514', 'A0520', 'B0743', 'A0343'],
      ctx='Confounder: Gewichtsverlust als Auslöser vs. Alter.'),
 dict(name='Emotionale Belastung (Schock, Traurigkeit, Wut, Scham)', f=AND(C(EMO), NOT(T('acceptance_aging', 'self_care_ritual', 'soft_smooth_desire', 'glow_desire', 'scent_love'))), ex=['A0061', 'A0144', 'B0862', 'A0521'],
      ctx='Kategorie „Emotional reactions“ gesamt; umfasst auch Akzeptanz-Stimmen.'),
]

# ===================== 05 OBJECTIONS =====================
OBJECTIONS = [
 dict(name='Geruch – v. a. AmLactin/Milchsäure („pee“, „sour milk“, „maple syrup“)', f=AND(OR(T('fragrance_sensitivity'), RX(r"\bpee\b|peed|urine|sour milk|maple|manure|stink")), C(OBJ, FAIL, SKEP, QUE, PHR, EMO)),
      ex=['A0299', 'A0302', 'C0395', 'A0047'], impl='Geruchsprofil ist bei der Benchmark-Kategorie (Milchsäure) der Haupteinwand – sensorische Akzeptanz als eigene Forschungsfrage prüfen; keine Aussagen über FALUNARA-Inhaltsstoffe ableiten.'),
 dict(name='Duft löst neu Reizung, Kopfschmerz, Unwohlsein aus', f=AND(T('fragrance_sensitivity'), RX(r"irritat|headache|itch|sensitiv|upset|allerg|hives|can't stand|cannot stand")),
      ex=['C0363', 'C0168', 'A0602', 'C0561'], impl='Duftintensität/-freiheit als Segmentierungsvariable prüfen (Peri-Kontext nur als Kontext).'),
 dict(name='Öl ist fettig, färbt ab, man muss warten bevor man sich anzieht', f=T('oil_greasy_staining'),
      ex=['B0087', 'C0170', 'A0476', 'A0172'], impl='Wartezeit bis „dressable“, Transfer auf Kleidung/Bettwäsche als zentrale Testkriterien für ein Körperöl.'),
 dict(name='Klebrig, filmig, „sits on top“', f=OR(T('sticky_film_texture'), AND(C(OBJ, FAIL, TAC, FRIC), RX(r"sticky|tacky|gluey|filmy|sits on top|sets on top"))),
      ex=['C0304', 'A0253', 'A0397', 'C0494'], impl='Klebrigkeit wird v. a. Lotionen/Actives zugeschrieben – Abgrenzungsfeld für Öl-Texturen (zu testen, nicht zu behaupten).'),
 dict(name='„Öl hydratisiert nicht, es versiegelt nur“', f=AND(T('oil_seals_not_hydrates'), C(ING, SKEP, OBJ, PREF)),
      ex=['C0505', 'C0095', 'A0422'], impl='Verbreitetes Laienmodell (Wasser + Okklusiv). Rolle eines Öls in der Routine muss erklärbar sein; Wirkversprechen nur mit belegten Inhaltsstoffdaten.'),
 dict(name='Zu teuer / Preis nicht gerechtfertigt', f=AND(T('price_value'), C(OBJ, SKEP, PUR, FAIL), RX(r"expensive|pricey|afford|\$|money|budget|spend|spent|cost|bank|price|cheap")),
      ex=['A0578', 'B0561', 'A0529', 'B0032'], impl='Preisanker (Costco-AmLactin, Drogerieöle) prägen Zahlungsbereitschaft; Premium braucht nachvollziehbare Begründung.'),
 dict(name='Marketing-Misstrauen: Hype, Buzzwords, keine Prozentangaben, Vorher/Nachher-Tricks', f=T('marketing_distrust'),
      ex=['C0641', 'C0463', 'A0185', 'A0449'], impl='Transparenz (INCI, Konzentrationen, ehrliche Bilder) ist Vertrauensvoraussetzung – Claims-Prüfung zwingend.'),
 dict(name='Topika können das nicht – nur Prozeduren, Training, Hormone', f=OR(AND(T('nothing_works', 'only_procedures_work', 'exercise_vs_topicals'), C(SKEP, OBJ, ING, EMO)), AND(T('hrt_estrogen_skin'), C(SKEP))),
      ex=['B0086', 'A0576', 'A0086', 'B0050'], impl='Erwartungsmanagement: Kategorie wird von vielen als kosmetisch-temporär gesehen; keine strukturellen Versprechen.'),
 dict(name='Reizung, Ausschlag, Brennen, Peeling durch Actives', f=AND(C(OBJ, FAIL, SKEP, QUE), RX(r"hives|rash|sting|burn|irritat|redness|peel|allerg")),
      ex=['A0295', 'A0509', 'B0668', 'C0352'], impl='Verträglichkeit als Kaufbarriere bei AHA/Retinol-Benchmarks.'),
 dict(name='Rutschige Dusche, schwer dosierbare Verpackung mit öligen Händen', f=T('oil_shower_packaging_friction'),
      ex=['C0042', 'C0179', 'C0488', 'A0597'], impl='In-Shower-Anwendung hat Sicherheits-/Praxis-Einwände; Packaging-Usability prüfen.'),
 dict(name='Inhaltsstoff-Ängste (Mineralöl, „Chemikalien“, Allergene)', f=T('ingredient_fear_clean'),
      ex=['A0479', 'A0445', 'A0048', 'C0485'], impl='Teil der Zielgruppe prüft INCI aktiv; Aussagen nur mit tatsächlicher Formel.'),
 dict(name='Reformulierung & Fälschungen', f=T('reformulation_counterfeit_distrust'),
      ex=['C0419', 'A0693', 'C0454', 'A0687'], impl='Vertrauen in Formelkonstanz und Bezugsquelle als Kaufkriterium.'),
 dict(name='Zu aufwendig / keine Zeit / vergesse es', f=AND(T('routine_fatigue', 'consistency_effort'), C(OBJ, FRIC)),
      ex=['B0563', 'C0313', 'B0519', 'A0264'], impl='Einfachheit und Einbindung in bestehende Momente (Dusche) als Hypothese.'),
 dict(name='Wirkung nur temporär – „Pick your poison“', f=OR(AND(T('lotion_temporary'), C(SKEP, OBJ, TIME)), RX(r"stop using|bandaid|band-aid|temporar|short.term")),
      ex=['A0746', 'B0237', 'B0015', 'B0023'], impl='Dauerhaftigkeit vs. tägliche Anwendung offen kommunizieren (Forschungsfrage, keine Copy).'),
 dict(name='Schwere/dicke Texturen sensorisch unangenehm', f=AND(C(OBJ, TAC, FRIC), RX(r"heavy|thick|hate the feel|feel of")),
      ex=['C0164', 'A0808', 'A0759'], impl='Sensorische Abneigung gegen „stuff on my body“ – Textur-Leichtigkeit testen.'),
]

# ===================== 06 FAILED SOLUTIONS =====================
FAILED = [
 dict(name='Duftende Massenmarkt-Lotionen (z. B. Bath & Body Works)', f=RX(r"Bath (&|and) Body|BBW|bath and body cream"),
      ex=['A0003', 'A0360', 'A0649', 'C0125'], out='„Duftet, pflegt aber nicht“ – Wechsel zu „Produkten, die die Haut verbessern“.'),
 dict(name='Normale Body-Lotions/Cremes allgemein', f=AND(T('lotion_temporary'), C(FAIL, SKEP, PROB, SYM, TAC)),
      ex=['C0194', 'B0088', 'B0356', 'C0349'], out='Nur kurzfristige Wirkung; Haut „schluckt“ mehr Produkt als früher.'),
 dict(name='AmLactin / Milchsäure-Lotion', f=AND(T('amlactin_lactic'), C(FAIL, OBJ, PHR)),
      ex=['B0023', 'A0275', 'A0295', 'A0302'], out='Für viele Benchmark-Erfolg, aber Misserfolge: nur kurzfristige Hydration, Geruch, Hives/Rash.'),
 dict(name='Gold Bond Crepe Corrector / Retinol Body', f=AND(T('gold_bond_crepe'), C(FAIL, OBJ, SKEP)),
      ex=['A0069', 'B0360', 'C0448', 'C0304'], out='Polarisiert: „jack squat“, kein Textur-Effekt, klebrig, Ausschläge nach vermuteter Reformulierung.'),
 dict(name='Crepe Erase', f=T('crepe_erase'), ex=['A0746', 'A0805', 'C0641'], out='Wirkt nur solange angewendet; „Buzzword“-Skepsis; günstigere Urea-Alternativen genannt.'),
 dict(name='Premium-/Prestige-Produkte (Osea, SkinMedica, L’Occitane …)', f=AND(RX(r"osea|ósea|o.shea|skinmedica|l'occitane|loccitane|sephora|fancy|luxury|prestige|expensive"), C(FAIL, SKEP, OBJ, PUR)),
      ex=['A0605', 'C0597', 'B0647', 'A0754'], out='„underwhelmed“, „did nothing“ – teure Käufe als Lehrgeld erzählt.'),
 dict(name='Körperöl allein / Öl + Lotion zu fettig', f=AND(OILT, C(FAIL, OBJ)),
      ex=['A0476', 'C0240', 'C0496'], out='Öl allein „too greasy“ oder „not enough“; Kombination wird zu fettig.'),
 dict(name='Retinol/Tretinoin am Körper', f=AND(T('retinol_body'), C(FAIL, OBJ, SKEP)),
      ex=['B0666', 'C0352', 'C0288', 'B0788'], out='Peeling/Austrocknung, Sonnen-Aufwand, unklare Dosierung, unsicherer Effekt.'),
 dict(name='Kollagen & Supplements', f=AND(T('collagen_supplement'), C(FAIL, SKEP, PUR)),
      ex=['B0838', 'B0808', 'B0511'], out='„still got that crepe“; Supplements „drain my bank account“.'),
 dict(name='Prozeduren (Microneedling, Laser, Neck-Tox)', f=AND(T('only_procedures_work'), C(FAIL, PUR, SKEP)),
      ex=['A0082', 'A0096', 'A0444', 'A0732'], out='Teuer, nicht dauerhaft, teils schlechter als vorher.'),
 dict(name='Krafttraining / Sport', f=AND(OR(T('exercise_vs_topicals'), RX(r"\blift|weight train|work ?out|exercise|training")), C(FAIL, SKEP, PROB, IDN)),
      ex=['B0026', 'B0797', 'A0129', 'B0830'], out='Muskeln fest, Haut bleibt crepey – Gegenstimme zur „lift weights“-Fraktion.'),
 dict(name='HRT/Östrogen (Kontext) – Haut bleibt', f=AND(T('hrt_estrogen_skin'), C(FAIL, SKEP)),
      ex=['A0224', 'A0166', 'B0759'], out='HRT hilft teils, aber nicht zuverlässig für Hände/Crepe – nur Kontext, kein Claim.'),
 dict(name='Mehr Wasser trinken', f=AND(T('hydration_water_belief'), C(FAIL, SKEP, EMO)),
      ex=['B0760', 'A0751'], out='Uneinheitlich: teils „massively dehydrated“, teils „way overblown“.'),
 dict(name='Peeling/Dry Brushing allein', f=AND(T('exfoliation_dry_brush'), C(FAIL, OBJ, FRIC, ING)),
      ex=['C0066', 'A0184', 'A0318'], out='Entfernt Schüppchen, „won’t tighten“; wird vergessen.'),
 dict(name='„Alles probiert“ – generelle Erschöpfung', f=AND(T('nothing_works'), C(FAIL)),
      ex=['B0762', 'C0648', 'B0702', 'A0616'], out='Serielle Fehlkäufe → Misstrauen gegenüber neuen Versprechen.'),
]

# ===================== 07 TRIGGERS =====================
TRIGGERS = [
 dict(name='Plötzliches Bemerken („overnight“, „woke up“, „last few months“)', f=T('sudden_onset'), ex=['A0099', 'B0020', 'B0390', 'A0111']),
 dict(name='Sommer / Kleidung, die Haut zeigt', f=T('summer_trigger', 'hiding_arms_sleeveless', 'shorts_dresses_avoidance'), ex=['B0223', 'A0782', 'A0459', 'C0316']),
 dict(name='Winter / trockenes oder wechselndes Klima', f=T('winter_dryness', 'climate_dryness'), ex=['A0018', 'C0046', 'A0641', 'B0361']),
 dict(name='Spiegel, Fotos, Gym, Schaufenster – Sichtmomente', f=OR(T('mirror_partner_moment'), AND(RX(r"mirror|reflection|photo|picture|\bgym\b|plank|light"), C(SIT, SYM, EMO, IDN, PHR))), ex=['A0160', 'A0188', 'A0157', 'B0181']),
 dict(name='Vergleich mit Mutter/Großmutter', f=T('mothers_skin'), ex=['B0826', 'B0829', 'A0850', 'B0227']),
 dict(name='Gewichtsverlust / GLP-1', f=T('weight_loss_glp1'), ex=['A0520', 'B0514', 'B0743', 'B0183']),
 dict(name='Peri-/Menopause (nur Kontext)', f=OR(T('hrt_estrogen_skin', 'menopause_symptom_context'), AND(F('hrt_medical_context'), C(SIT, PHR, EMO)), RX(r"menopaus|\bperi\b")), ex=['A0167', 'B0562', 'C0115', 'C0297']),
 dict(name='Heiß duschen/baden, Rasieren', f=OR(T('shower_bath_shaving_trigger'), RX(r"hot shower|hot water|hot bath|shav")), ex=['C0115', 'C0160', 'A0748', 'C0644']),
 dict(name='Moment direkt nach der Dusche (Anwendungsmoment, feuchte Haut)', f=T('oil_on_damp_skin'), ex=['A0672', 'B0544', 'C0474', 'C0039']),
 dict(name='Abend/Bett/Bettwäsche', f=AND(RX(r"\bbed\b|sheets|\bnight|sleep"), C(FRIC, SIT, PREF, OBJ, QUE, TAC)), ex=['A0253', 'C0111', 'C0297', 'A0263']),
 dict(name='Anziehen nach dem Eincremen (Kleidung, Robe, Stoffe)', f=AND(RX(r"\bdress\b|dressed|clothes|clothing|robe|fabric"), C(FRIC, OBJ, PUR, QUE, PREF)), ex=['B0087', 'A0347', 'C0502', 'A0607']),
 dict(name='Alters-Meilenstein (40, 45, 50 …)', f=RX(r"turned \d\d|turning \d\d|hit my \d\d|until I turned"), ex=['B0390', 'A0119', 'B0398', 'C0275']),
 dict(name='Empfehlungen anderer (Reddit, Familie, Derm)', f=T('peer_proof', 'derm_recommendation'), ex=['A0187', 'A0346', 'A0077', 'A0580']),
 dict(name='Werbung/Social-Media-Impulse', f=AND(RX(r"\bads?\b|facebook|tiktok|instagram|influencer|doom ?scroll|bombarded"), NOT(RX(r"doomed"))), ex=['C0533', 'A0571', 'A0255', 'C0482']),
 dict(name='Arzt/Derm sagt „das ist Alter“', f=OR(AND(T('derm_recommendation'), C(SKEP, PROB)), T('betrayal_unprepared')), ex=['A0095', 'B0179', 'C0666']),
]

# ===================== 08 PHRASE BANK (term level) =====================
PHRASES = [
 (r"crep", 'crepey / crepe / crepiness / crepefication', 'Problem-Kernbegriff', 'Selbstbezeichnung der Zielgruppe; Schreibvarianten „crepy“, „crepiness“.'),
 (r"\bcreepy\b", '„creepy skin“ (Falschschreibung)', 'Problem-Kernbegriff', 'Häufige Verschreibung – relevant für Suchbegriffe.'),
 (r"overnight", 'overnight', 'Trigger/Onset', 'Kern des Sudden-onset-Narrativs.'),
 (r"woke up|wake up", 'woke up (with/to)', 'Trigger/Onset', ''),
 (r"lizard|reptil|snake|alligator|crocodile|dragon|dinosaur|scales|scaly", 'Reptil-Metaphern (lizard, snake, alligator, crocodile, dragon scales, dinosaur, scaly)', 'Metapher (Textur)', 'Stärkste Bildfamilie für Textur.'),
 (r"desert|raisin|prune|mummy|leather|parched", 'Austrocknungs-Metaphern (desert, raisin, prune, mummy, leathery, parched)', 'Metapher (Trockenheit)', ''),
 (r"tissue paper|crinkl|crepe paper|crumpled", 'tissue paper / crinkle / crepe paper', 'Metapher (Textur)', ''),
 (r"grandma|granny|grandmother", 'grandma / granny (hands, arms)', 'Identität', ''),
 (r"old lady|old woman|old-people|old person|old people", 'old lady / old woman / old-people-legs', 'Identität', ''),
 (r"\bmother|\bmom\b|\bmum\b|\bMIL\b", 'mother / mom / MIL', 'Identität', 'Generationsvergleich.'),
 (r"turkey", 'turkey neck', 'Identität (Hals)', 'Körpernah, Halsbereich.'),
 (r"chicken wing|bat wing|\bwings\b|arm flaps", 'bat wings / chicken wings', 'Identität (Arme)', ''),
 (r"sleeve", 'sleeve(s) / sleeveless', 'Verhalten (Verstecken)', ''),
 (r"\bshorts\b|skirt|sundress", 'shorts / skirts / sundress', 'Verhalten (Verstecken)', ''),
 (r"dandruff|flak|peel", 'flaking / peeling / body dandruff', 'Symptom', ''),
 (r"itch", 'itchy / itching', 'Symptom', ''),
 (r"\bthin\b|see-through|tissue", 'thin / see-through skin', 'Symptom', ''),
 (r"\bsoft", 'soft (as a baby’s butt/bottom)', 'Desire (taktil)', 'Häufigster positiver Zielbegriff.'),
 (r"smooth", 'smooth', 'Desire (taktil)', ''),
 (r"supple", 'supple', 'Desire (taktil)', ''),
 (r"plump", 'plump / plumped up', 'Desire (taktil/visuell)', ''),
 (r"glow|shiny|sheen", 'glow / glowy / sheen', 'Desire (visuell)', ''),
 (r"look human", 'look human again', 'Desire (Identität)', 'Isoliert, aber prägnant.'),
 (r"game.?changer", 'game changer', 'Erfolg', 'Typisches Erfolgsvokabular.'),
 (r"miracle|magic|holy grail|god ?send", 'miracle / magic / holy grail / godsend', 'Erfolg', ''),
 (r"slather|slug", 'slather / slugging', 'Anwendung', ''),
 (r"damp|wet skin|still wet|before (I )?(dry|towel)|out of the shower|after (my |the |a )?shower", 'on damp/wet skin, out of the shower', 'Anwendung', 'Nahezu Konsens-Anwendungsmoment.'),
 (r"lock(s|ed)? (it |in |the )|seal", 'lock in / seal (in)', 'Mechanismus-Glaube', 'Laienmodell Öl = Versiegelung.'),
 (r"absorb|sink(s)? in|soak(s|ed)? (it )?(in|up)|rub in", 'absorbs / sinks in / soaks in', 'Kaufkriterium', ''),
 (r"greas|grease|oily|slick", 'greasy / oily / slick', 'Objection', ''),
 (r"sticky|tacky|gluey", 'sticky / tacky / gluey', 'Objection', ''),
 (r"\bstain|ruin|discolor|transfer", 'stain / ruin / transfer (clothes, sheets)', 'Objection', ''),
 (r"\bpee\b|peed|urine|sour milk|maple|manure|smells? like", 'smells like … (pee, sour milk, maple syrup)', 'Objection (Geruch)', 'Überwiegend AmLactin.'),
 (r"fragrance.free|unscented", 'fragrance-free / unscented', 'Kaufkriterium', ''),
 (r"band-?aid|temporar|short.term|pick your poison", 'temporary / bandaid / pick your poison', 'Skepsis', ''),
 (r"\bhype|buzzword|marketing|gimmick|scam", 'hype / buzzword / marketing / gimmick', 'Skepsis', ''),
 (r"nothing works|nothing (is )?help|tried everything|tried (almost|all)|nothing (seems to|will)", 'nothing works / tried everything', 'Skepsis', ''),
 (r"waste (of )?(my )?money|save your money|break the bank|\$\d", 'waste of money / save your money / $-Anker', 'Preis', ''),
]

# ===================== 09 PATTERNS =====================
PATTERNS = [
 dict(key='P01', name='Öl auf feuchter Haut direkt nach/in der Dusche ist die dominante, fast konsensuelle Öl-Praxis', f=T('oil_on_damp_skin'),
      ex=['A0672', 'B0544', 'C0474'], counter=['B0563', 'C0042', 'C0179'], cnote='Ungeduld/Wartezeit und rutschige Dusche als Gegenstimmen.'),
 dict(key='P02', name='Lotion wirkt nur kurz → Nachcreme-Zyklus; Konsistenz wird als Schlüssel UND als Last erlebt', f=T('lotion_temporary', 'consistency_effort'),
      ex=['C0194', 'C0092', 'A0125'], counter=['A0823', 'A0192', 'B0515'], cnote='Einzelne berichten schnelle, anhaltende Verbesserung.'),
 dict(key='P03', name='Einziehen ohne Fett/Klebrigkeit ist das Gatekeeper-Kaufkriterium (Anziehen, Bettwäsche)', f=T('oil_absorbs_fast', 'oil_greasy_staining', 'sticky_film_texture', 'texture_weight_preference'),
      ex=['C0093', 'C0170', 'A0253'], counter=['A0132', 'C0592', 'A0649'], cnote='Eine Gruppe bevorzugt bewusst „heavy, heavy“ Texturen.'),
 dict(key='P04', name='Verwirrung über Öl vs. Lotion und die Reihenfolge; Laienmodell „Öl versiegelt nur“', f=T('oil_vs_lotion_confusion', 'question_order_of_application', 'oil_seals_not_hydrates'),
      ex=['C0503', 'C0608', 'C0505'], counter=['B0581', 'A0404', 'B0494'], cnote='Widersprüchliche Ratschläge zu Reihenfolge und Penetration.'),
 dict(key='P05', name='Duft polarisiert: Duftliebe vs. Duftempfindlichkeit/Geruchseinwand', f=T('fragrance_sensitivity', 'scent_love'),
      ex=['A0299', 'C0363', 'C0497'], counter=['C0291', 'A0021'], cnote='Beide Seiten stark; „fake plastic smell“ unparfümierter Produkte als Gegenargument.'),
 dict(key='P06', name='AmLactin (Milchsäure) ist der Community-Benchmark – mit Geruch als Haupteinwand', f=T('amlactin_lactic'),
      ex=['A0017', 'A0187', 'A0302'], counter=['B0023', 'A0275', 'A0295'], cnote='Misserfolge, Hives, nur kurzfristige Hydration.'),
 dict(key='P07', name='Gold Bond Crepe Corrector polarisiert (Schnell-Erfolg vs. „jack squat“, klebrig, Ausschlag)', f=T('gold_bond_crepe'),
      ex=['C0105', 'A0776', 'A0069'], counter=['C0304', 'B0360', 'C0448'], cnote='Pattern IST der Widerspruch.'),
 dict(key='P08', name='Plötzlicher Beginn („overnight“) als Schock-Narrativ, Alter 40–65', f=T('sudden_onset'),
      ex=['A0099', 'B0020', 'B0390'], counter=['C0205', 'B0869'], cnote='Einige beschreiben schleichende, vorhersehbare Veränderung.'),
 dict(key='P09', name='Alterungs-Identität: „old lady“, Großmutter/Mutter-Haut, Reptil-Metaphern', f=T('old_lady_identity', 'mothers_skin', 'texture_metaphor'),
      ex=['B0865', 'A0716', 'B0829'], counter=['B0211', 'A0215'], cnote='Akzeptanz-Stimmen („Just love yourself“).'),
 dict(key='P10', name='Verstecken & Kleidung: lange Ärmel, keine Shorts; Sommer als Auslöser', f=T('hiding_arms_sleeveless', 'shorts_dresses_avoidance', 'summer_trigger'),
      ex=['C0636', 'A0080', 'B0223'], counter=['A0148', 'B0124'], cnote='„screw it“ – trotzdem Shorts tragen.'),
 dict(key='P11', name='Preis-Wert-Sensibilität; günstige Öle/Drogerie als Referenz', f=T('price_value', 'cheap_oil_alternative'),
      ex=['A0124', 'B0258', 'C0096'], counter=['A0406', 'A0754'], cnote='„Pricey, but … pickier“ – Zahlungsbereitschaft für Qualität existiert.'),
 dict(key='P12', name='Marketing-Misstrauen, Transparenzforderung (Prozente, INCI, Fotos)', f=T('marketing_distrust', 'reformulation_counterfeit_distrust'),
      ex=['C0463', 'C0641', 'A0185'], counter=['A0252', 'A0830'], cnote='Vorher/Nachher-Fotos und Branchen-Empfehlungen überzeugen dennoch einige.'),
 dict(key='P13', name='Topischer Fatalismus: nichts wirkt dauerhaft; „echte“ Lösungen = Prozeduren, Training, Hormone', f=T('nothing_works', 'only_procedures_work', 'exercise_vs_topicals'),
      ex=['B0086', 'A0576', 'A0086'], counter=['B0216', 'B0851', 'B0026'], cnote='Viele Erfolgsberichte mit Topika; Training hilft der Haut nicht immer.'),
 dict(key='P14', name='Akzeptanz/Dankbarkeit als starke Gegenstimme', f=T('acceptance_aging'),
      ex=['A0215', 'B0211', 'A0163'], counter=['C0199', 'B0865'], cnote='Explizite Ablehnung von „embrace“.'),
 dict(key='P15', name='Routine-Müdigkeit vs. Pflege als Ritual', f=T('routine_fatigue', 'self_care_ritual'),
      ex=['A0673', 'C0034', 'B0439'], counter=['B0595', 'C0243'], cnote='Ritual-Genuss als Gegenpol.'),
 dict(key='P16', name='Taktile Ziele (soft/smooth/supple) dominieren vor visuellen (glow)', f=T('soft_smooth_desire', 'glow_desire'),
      ex=['A0017', 'B0252', 'C0629'], counter=['B0015'], cnote='„temporarily plumps … won’t make a noticeable difference on crepey skin“.'),
 dict(key='P17', name='Körperzonen-Hierarchie: Arme > Beine > Hände > Hals > Knie/Brust/Bauch (Body area & Tags)', f=T('crepey_arms', 'crepey_legs', 'crepey_hands', 'crepey_knees', 'crepey_chest', 'crepey_abdomen'),
      ex=['B0092', 'A0130', 'A0632'], counter=['B0892'], cnote='Bauch als schwer behandelbare Ausnahmezone.'),
 dict(key='P18', name='Körper als vernachlässigte Zone neben dem Gesicht; Gesichts-Reste auf den Körper', f=T('body_neglect_vs_face', 'face_product_transfer'),
      ex=['A0001', 'C0422', 'B0340'], counter=['A0262'], cnote='Körperhaut braucht „different things“.'),
 dict(key='P19', name='Peri-/Menopause & HRT als Kontext (Flag hrt_medical_context) – nicht als Produktclaim', f=OR(T('hrt_estrogen_skin', 'menopause_symptom_context'), F('hrt_medical_context')),
      ex=['A0167', 'B0159', 'B0722'], counter=['A0224', 'A0166', 'C0233'], cnote='HRT hilft nicht allen; Skepsis gegenüber HRT-„Wunder“.'),
 dict(key='P20', name='Gewichtsverlust/GLP-1 als Auslöser', f=T('weight_loss_glp1'),
      ex=['A0520', 'B0514', 'B0743'], counter=[], cnote='Keine direkte Gegenevidenz; Confounder zu Alter.'),
 dict(key='P21', name='Zeit-bis-Ergebnis: „next day/1–2 Wochen“ (Gefühl) vs. „3–6 Monate+“ (sichtbare Veränderung)', f=T('time_to_result'),
      ex=['A0823', 'A0525', 'B0851'], counter=['A0615', 'A0331'], cnote='Nach Monaten keine Wirkung / schlechter.'),
 dict(key='P22', name='Juckreiz/Schuppen als Komfortproblem (v. a. Menopause-Communities)', f=T('itch_flake'),
      ex=['A0670', 'C0250', 'C0160'], counter=['A0018'], cnote='Mit Pflege „zero flaking“.'),
 dict(key='P23', name='Saisonalität: Winter/trockenes Klima verstärkt, Sommer exponiert', f=T('winter_dryness', 'climate_dryness', 'summer_trigger'),
      ex=['C0046', 'A0641', 'A0426'], counter=['C0493'], cnote='Im feuchten Klima „won’t dry“.'),
 dict(key='P24', name='Inhaltsstoff-Ängste & Natürlichkeits-Präferenz (Mineralöl, „chemicals“, Tallow, Pflanzenöle)', f=T('ingredient_fear_clean', 'natural_botanical_pref'),
      ex=['A0479', 'C0277', 'A0416'], counter=['A0412', 'A0417'], cnote='„professionally formulated“ / „synthetics can get you great results“.'),
 dict(key='P25', name='Peer-Proof: Reddit-Empfehlungen lösen Käufe aus', f=T('peer_proof'),
      ex=['A0187', 'A0077', 'A0346'], counter=['A0054', 'A0314'], cnote='Verdacht auf Social-Media-Team; Geruchswarnungen aus Reddit.'),
]

CONTRA = [
 ('Öl zuerst oder Lotion zuerst?', ['B0605', 'C0400'], ['C0035', 'C0132'], 'Beide Reihenfolgen werden als „richtig“ dargestellt; keine Einigkeit im Corpus.'),
 ('Hydratisiert Öl oder versiegelt es nur?', ['C0505', 'C0095'], ['B0581', 'A0404'], 'Laienmodell „nur Okklusiv“ vs. „penetrieren“/„much more absorbent“.'),
 ('Duft: Genuss vs. Unverträglichkeit', ['C0291', 'C0497'], ['C0363', 'C0168'], 'Gleiches Segment, gegensätzliche Präferenzen – teils sogar dieselbe Person im Zeitverlauf (C0364).'),
 ('AmLactin: Wundermittel vs. Geruch/Reaktion/Wirkungslosigkeit', ['A0017', 'A0187'], ['A0302', 'B0023'], 'Benchmark mit hoher Polarisierung.'),
 ('Gold Bond Crepe Corrector: Sofort-Erfolg vs. „jack squat“', ['A0776', 'C0105'], ['A0069', 'C0304'], 'Klassischer Polarisierungsfall.'),
 ('Training hilft vs. hilft der Haut nicht', ['A0086', 'B0011'], ['B0026', 'A0654'], 'A0654 ist under_40 – Gewicht reduziert.'),
 ('Topika sind sinnlos vs. Topika haben mir geholfen', ['B0086', 'A0576'], ['B0216', 'B0851'], 'Fatalismus und Erfolgsberichte koexistieren.'),
 ('Schnelle Ergebnisse vs. Monate', ['A0823', 'A0192'], ['B0851', 'A0331'], 'Gefühlte Weichheit sofort, sichtbare Textur erst nach Monaten (Interpretation).'),
 ('Akzeptanz vs. Ablehnung von „embrace“', ['A0215', 'B0211'], ['C0199', 'B0865'], 'Beide Haltungen sind legitim und häufig.'),
 ('Wasser trinken entscheidend vs. überbewertet', ['B0292', 'B0726'], ['A0751'], 'Kleine Basis – niedrige Konfidenz.'),
 ('Schwere Texturen vs. leichte Texturen', ['A0132', 'C0592'], ['C0164', 'C0086'], 'Texturpräferenz ist segmentabhängig.'),
 ('Günstig reicht vs. Premium lohnt', ['C0097', 'C0463'], ['A0406', 'A0754'], 'Mehrheit preissensibel, Minderheit qualitätsorientiert.'),
 ('HRT als Lösung vs. HRT hilft der Haut nicht', ['B0212', 'B0159'], ['A0224', 'A0166'], 'Nur Kontext; keine Produktaussage.'),
]

CURATED = ['A0001', 'A0613', 'B0020', 'B0390', 'C0377', 'B0188', 'A0670', 'C0250', 'A0632', 'B0829', 'A0080', 'B0089', 'C0636', 'B0806', 'A0042',
           'C0346', 'B0865', 'B0796', 'A0814', 'A0111',
           'A0003', 'A0004', 'B0023', 'A0069', 'C0448', 'C0194', 'B0088', 'C0240', 'B0237', 'A0746', 'B0086', 'B0838',
           'A0672', 'B0544', 'C0474', 'C0505', 'C0095', 'A0404', 'A0476', 'B0087', 'C0170', 'C0042', 'C0503', 'C0608', 'C0451',
           'C0093', 'A0347', 'C0538', 'B0258', 'A0750', 'C0463', 'C0641', 'C0269', 'C0497', 'A0185', 'C0533',
           'A0299', 'C0363', 'C0291',
           'A0017', 'B0252', 'C0353', 'B0804', 'C0629', 'B0279',
           'A0099', 'B0514', 'A0160', 'C0115', 'A0525', 'B0851']
